Model browsing
sys-bio/vscode-antimony pull request #132
Opened 2023-01-20 08:07 UTC by shshdhdhdhdyx

Biomodel browsing:

Users can right click anywhere on the screen to see an option called "Browse Biomodels", which will show a search box for users to enter their desired query and search for biomodel(s). They then get a list of results that display the models most closely related to their query, or a single model if they enter a specific model number. They can then click on the desired model, which will pop up in a separate tab as a temp file, converted to Antimony and with all the features available in the extension. They can then modify the model as needed and save it in SBML or Antimony, according to their needs.

2023-01-23 07:10 UTC, longxf21 requested changes

2023-01-23 07:10 UTC, longxf21 commented on vscode-antimony/src/server/stibium/stibium/antimony.lark
> +    | "origin"
Highlight these in src/syntax/antimony.tmLanguage.json

2023-01-23 07:10 UTC, longxf21 commented on vscode-antimony/src/server/main.py
> +    vscode_logger.info("SBML conversion passed")
Delete loggers

2023-01-23 07:10 UTC, longxf21 commented on vscode-antimony/src/server/main.py
> +    vscode_logger.info(data)
delete logger

2023-01-26 03:26 UTC, longxf21 requested changes

2023-01-26 03:26 UTC, longxf21 commented on vscode-antimony/src/server/main.py
> +        vscode_logger.info("SBML conversion failed")
Delete this logger. If you want to display this to user, use vscode error message

2023-01-26 03:26 UTC, longxf21 commented on vscode-antimony/src/modelBrowse.ts
> +                console.log("it was successful!")
Delete this log

2023-01-26 03:26 UTC, longxf21 commented on vscode-antimony/src/modelBrowse.ts
> +                    console.log("Written to file")
Delete this log, or have a better logging message

2023-01-26 03:26 UTC, longxf21 commented on vscode-antimony/src/modelBrowse.ts
> +                    window.showErrorMessage(`Could not perform query: ${result.error}`).then(() => console.log('finished'));
Why a console log and .then() here?

2023-01-29 23:31 UTC, evaliu2002 requested changes
Line 492's indentation off. Otherwise should look good. Check Aldrich's review

2023-01-30 19:54 UTC, evaliu2002 approved these changes

2023-01-30 23:29 UTC, merged